import { fontFamily } from '@/theme/typography';
import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  safe: { flex: 1 },
  flex: { flex: 1 },
  topBar: {
    minHeight: 68,
    paddingHorizontal: 20,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topHeading: { flex: 1 },
  topEyebrow: { fontSize: 10, lineHeight: 14, fontFamily: fontFamily.extrabold, letterSpacing: 1.2 },
  topTitle: { fontSize: 20, lineHeight: 26, fontFamily: fontFamily.extrabold },
  scroll: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 48 },
  hero: {
    borderRadius: 28,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 20,
  },
  badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  badge: {
    minHeight: 30,
    paddingHorizontal: 10,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  badgeText: { fontSize: 12, fontFamily: fontFamily.bold },
  capitalize: { textTransform: 'capitalize' },
  heroTitle: { fontSize: 30, lineHeight: 37, fontFamily: fontFamily.extrabold, marginTop: 18, marginBottom: 20 },
  scheduleLine: {
    paddingTop: 17,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  scheduleIcon: { width: 44, height: 44, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  scheduleCopy: { flex: 1 },
  scheduleDate: { fontSize: 15, lineHeight: 21, fontFamily: fontFamily.bold },
  scheduleMeta: { marginTop: 2, fontSize: 13, lineHeight: 19, fontFamily: fontFamily.medium },
  sectionTitle: { marginTop: 26, marginBottom: 9, marginLeft: 4, fontSize: 11, fontFamily: fontFamily.extrabold, letterSpacing: 1.1 },
  group: {
    borderRadius: 24,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  infoRow: { minHeight: 76, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12 },
  notesRow: { alignItems: 'flex-start' },
  rowIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  rowCopy: { flex: 1 },
  rowLabel: { fontSize: 15, lineHeight: 20, fontFamily: fontFamily.bold },
  rowDescription: { marginTop: 3, fontSize: 12, lineHeight: 17, fontFamily: fontFamily.medium },
  notesText: { marginTop: 5, fontSize: 14, lineHeight: 21 },
  divider: { height: StyleSheet.hairlineWidth, marginLeft: 70 },
  trailingAction: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  deleteBtn: {
    minHeight: 52,
    marginTop: 18,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  deleteText: { fontSize: 15, fontFamily: fontFamily.bold },
  missingBack: { padding: 16 },
  missingState: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  missingTitle: { fontSize: 16, fontFamily: fontFamily.semibold },
});
