import { StyleSheet } from 'react-native';
import { radii } from '@/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: 'transparent' },
  content: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 124 },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 26 },
  headerCopy: { flex: 1 },
  headerActions: { flexDirection: 'row', gap: 10, alignItems: 'center' },
  eyebrow: { fontSize: 13, lineHeight: 18, fontWeight: '500', marginBottom: 2 },
  title: { fontSize: 27, lineHeight: 32, fontWeight: '700', letterSpacing: -0.5 },
  avatar: { width: 44, height: 44, borderRadius: 22, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#FFF', fontSize: 17, fontWeight: '700' },
  dateHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  sectionTitle: { fontSize: 19, lineHeight: 25, fontWeight: '700', letterSpacing: -0.2 },
  dateLabel: { fontSize: 13, lineHeight: 18, marginTop: 2 },
  weekCard: { marginBottom: 28, borderRadius: radii.xl },
  weekRow: { flexDirection: 'row', justifyContent: 'space-between' },
  day: { width: 42, minHeight: 66, borderRadius: 17, borderWidth: 1, borderColor: 'transparent', alignItems: 'center', justifyContent: 'center' },
  dayName: { fontSize: 11, fontWeight: '600', marginBottom: 4 },
  dayNumber: { fontSize: 16, fontWeight: '700' },
  dayDot: { width: 4, height: 4, borderRadius: 2, marginTop: 5 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 13, marginTop: 2 },
  sectionSub: { fontSize: 12, lineHeight: 17, marginTop: 1 },
  inlineAction: { flexDirection: 'row', alignItems: 'center', gap: 4, minHeight: 44, paddingLeft: 12 },
  inlineActionText: { fontSize: 13, fontWeight: '600' },
  horizontalList: { gap: 12, paddingRight: 20, paddingBottom: 25 },
  eventCard: { width: 188, height: 160 },
  eventTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  eventIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  priorityDot: { width: 8, height: 8, borderRadius: 4 },
  eventTitle: { fontSize: 15, lineHeight: 20, fontWeight: '700', minHeight: 40, marginBottom: 8 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 3 },
  metaText: { flex: 1, fontSize: 11, lineHeight: 15 },
  emptyEvent: { width: 250, minHeight: 176 },
  emptyTitle: { fontSize: 15, lineHeight: 20, fontWeight: '700', marginTop: 10 },
  emptyCopy: { fontSize: 12, lineHeight: 17, marginTop: 3, marginBottom: 12 },
  metricsRow: { flexDirection: 'row', gap: 12, marginBottom: 28 },
  metricTouch: { flex: 1 },
  metricCard: { minHeight: 172 },
  metricTop: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 18 },
  metricIcon: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  metricKicker: { fontSize: 12, fontWeight: '600', flexShrink: 1 },
  metricValue: { fontSize: 27, lineHeight: 32, fontWeight: '700', fontVariant: ['tabular-nums'] },
  alarmValue: { fontSize: 21, lineHeight: 32, fontWeight: '700', fontVariant: ['tabular-nums'] },
  metricMeta: { fontSize: 11, lineHeight: 16, marginTop: 2, marginBottom: 12 },
  progressTrack: { height: 6, borderRadius: 3, overflow: 'hidden', marginTop: 'auto' },
  progressFill: { height: 6, borderRadius: 3 },
  addButton: { minHeight: 42, paddingHorizontal: 15 },
  agendaCard: { marginBottom: 20 },
  agendaRow: { minHeight: 76, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, marginHorizontal: 14 },
  agendaIcon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  agendaCopy: { flex: 1, marginRight: 8 },
  agendaTitle: { fontSize: 15, lineHeight: 20, fontWeight: '600' },
  agendaMeta: { fontSize: 12, lineHeight: 17, marginTop: 2 },
  agendaEmpty: { alignItems: 'center', padding: 28 },
});
