import { StyleSheet } from 'react-native';

import { fontFamily } from '@/theme/typography';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: 'transparent' },
  content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 112 },

  header: { minHeight: 90, flexDirection: 'row', alignItems: 'flex-start' },
  headerCopy: { flex: 1, minWidth: 0, paddingRight: 10 },
  greeting: { fontSize: 18, lineHeight: 23, fontFamily: fontFamily.semiboldItalic },
  name: { marginTop: -2, fontSize: 36, lineHeight: 41, fontFamily: fontFamily.black, letterSpacing: -1.1 },
  encouragement: { marginTop: 2, fontSize: 14, lineHeight: 19, fontFamily: fontFamily.medium },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  avatar: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },
  avatarGradient: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, borderRadius: 26 },
  avatarPhoto: { width: 52, height: 52, borderRadius: 26 },
  avatarText: { fontSize: 20, lineHeight: 25, fontFamily: fontFamily.bold },

  glyphSurface: { alignItems: 'center', justifyContent: 'center' },

  dateLine: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
  dateIcon: { width: 34, height: 34, borderRadius: 11 },
  fullDate: { flexShrink: 1, fontSize: 15, lineHeight: 20, fontFamily: fontFamily.bold },

  weatherCard: { minHeight: 104, marginBottom: 10 },
  weatherState: { minHeight: 104, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
  weatherStateIcon: { width: 42, height: 42, borderRadius: 21 },
  weatherStateCopy: { flex: 1, minWidth: 0 },
  weatherStateTitle: { fontSize: 15, lineHeight: 20, fontFamily: fontFamily.extrabold },
  weatherStateText: { flexShrink: 1, marginTop: 2, fontSize: 12, lineHeight: 16, fontFamily: fontFamily.regular },
  weatherAction: { minHeight: 44, paddingHorizontal: 14 },
  weatherReady: { minHeight: 104, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center' },
  weatherArtwork: { width: 54, height: 54, marginLeft: -2 },
  temperature: { marginLeft: 2, fontSize: 34, lineHeight: 40, fontFamily: fontFamily.black, letterSpacing: -1, fontVariant: ['tabular-nums'] },
  weatherCondition: { flex: 1, minWidth: 52, marginLeft: 7 },
  conditionLabel: { fontSize: 13, lineHeight: 18, fontFamily: fontFamily.extrabold },
  feelsLike: { marginTop: 1, fontSize: 10.5, lineHeight: 14, fontFamily: fontFamily.regular },
  weatherDivider: { width: 1, height: 48, marginHorizontal: 7 },
  weatherDetail: { width: 43, alignItems: 'center' },
  weatherDetailLabel: { marginTop: 2, fontSize: 9.5, lineHeight: 12, fontFamily: fontFamily.semibold },
  weatherDetailValue: { marginTop: 1, fontSize: 11, lineHeight: 15, fontFamily: fontFamily.extrabold },
  weatherChevron: { width: 28, height: 28, marginLeft: 3, borderRadius: 10 },

  overviewCard: { flex: 1, minWidth: 0 },
  overviewRow: { minHeight: 104, marginBottom: 10, flexDirection: 'row', alignItems: 'stretch', gap: 10 },
  overviewItem: { flex: 1, minWidth: 0, minHeight: 104, paddingHorizontal: 11, paddingVertical: 12, flexDirection: 'row', alignItems: 'center' },
  overviewIcon: { width: 40, height: 40, borderRadius: 13, marginRight: 9 },
  overviewCopy: { flex: 1, minWidth: 0 },
  overviewLabel: { fontSize: 11, lineHeight: 15, fontFamily: fontFamily.extrabold },
  overviewValue: { marginTop: 1, fontSize: 23, lineHeight: 28, fontFamily: fontFamily.black, letterSpacing: -0.6, fontVariant: ['tabular-nums'] },
  overviewMeta: { marginTop: 1, fontSize: 9.5, lineHeight: 13, fontFamily: fontFamily.medium },

  planningStack: { gap: 10, marginBottom: 10 },
  sectionCard: { minWidth: 0 },
  sectionHeading: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  sectionHeadingCopy: { flex: 1, minWidth: 0 },
  sectionTitle: { flexShrink: 1, fontSize: 13, lineHeight: 17, fontFamily: fontFamily.black, textTransform: 'uppercase', letterSpacing: 0.1 },
  sectionSubtitle: { marginTop: 2, fontSize: 10, lineHeight: 14, fontFamily: fontFamily.medium },
  sectionAction: { minHeight: 44, marginRight: -4, paddingLeft: 12, paddingRight: 4, flexDirection: 'row', alignItems: 'center', gap: 4 },
  sectionActionText: { fontSize: 12, lineHeight: 16, fontFamily: fontFamily.extrabold },

  timelineRow: { minHeight: 48, flexDirection: 'row', alignItems: 'stretch' },
  timelineTime: { width: 58, paddingTop: 6, fontSize: 11, lineHeight: 15, fontFamily: fontFamily.bold, fontVariant: ['tabular-nums'] },
  timelineRail: { width: 18, alignItems: 'center' },
  timelineDot: { width: 10, height: 10, marginTop: 8, borderRadius: 5, borderWidth: 1 },
  timelineLine: { position: 'absolute', top: 18, bottom: -6, width: 1 },
  timelineCopy: { flex: 1, minWidth: 0, paddingLeft: 6, paddingTop: 3 },
  timelineTitle: { fontSize: 13, lineHeight: 18, fontFamily: fontFamily.bold },
  timelineMeta: { marginTop: 1, fontSize: 11, lineHeight: 15, fontFamily: fontFamily.regular },

  taskRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 10 },
  checkbox: { width: 24, height: 24, borderRadius: 7, borderWidth: 1.5, backgroundColor: 'rgba(255,255,255,0.20)' },
  taskCopy: { flex: 1, minWidth: 0, justifyContent: 'center', minHeight: 48 },
  taskTitle: { fontSize: 13, lineHeight: 18, fontFamily: fontFamily.bold },
  taskMeta: { marginTop: 1, fontSize: 11, lineHeight: 15, fontFamily: fontFamily.semibold },
  addTask: { minHeight: 48, marginTop: 10, borderRadius: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  addTaskText: { fontSize: 13, lineHeight: 18, fontFamily: fontFamily.extrabold },

  compactEmpty: { minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 8 },
  emptyIcon: { width: 42, height: 42, borderRadius: 13 },
  emptyCopy: { flex: 1, minWidth: 0 },
  emptyTitle: { fontSize: 14, lineHeight: 19, fontFamily: fontFamily.extrabold },
  emptyText: { marginTop: 2, fontSize: 11, lineHeight: 15, fontFamily: fontFamily.regular },
  emptyAction: { minHeight: 44, marginTop: 0, paddingHorizontal: 12 },

  outlookCard: { minWidth: 0 },
  insightBody: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 11 },
  insightIcon: { width: 42, height: 42, borderRadius: 13 },
  insightText: { flex: 1, fontSize: 12, lineHeight: 17, fontFamily: fontFamily.medium },
});
