import { fontFamily } from '@/theme/typography';
import React from 'react';
import { Modal, Pressable, StyleSheet, TouchableOpacity, View } from 'react-native';
import { AppText as Text } from '@/components/ui/AppText';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';

import { useTheme } from '@/context/ThemeContext';

export function NewNoteSheet({ visible, onClose, onCreateNote, onCreateChecklist }: { visible: boolean; onClose: () => void; onCreateNote: () => void; onCreateChecklist: () => void }) {
  const { theme } = useTheme();
  const choose = (action: () => void) => { onClose(); action(); };
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={styles.layer}><Pressable accessibilityLabel="Close new note menu" style={StyleSheet.absoluteFill} onPress={onClose} /><SafeAreaView edges={['bottom']} style={[styles.sheet, { backgroundColor: theme.glass.solid, borderColor: theme.glass.border }]}><View style={[styles.handle, { backgroundColor: theme.divider }]} /><View style={styles.headingRow}><View><Text style={[styles.title, { color: theme.content.primary }]}>Create</Text><Text style={[styles.subtitle, { color: theme.content.secondary }]}>Start simple. You can add photos and lists later.</Text></View><TouchableOpacity accessibilityLabel="Close" style={styles.close} onPress={onClose}><Ionicons name="close" size={22} color={theme.content.primary} /></TouchableOpacity></View><TouchableOpacity style={[styles.option, { borderBottomColor: theme.divider }]} onPress={() => choose(onCreateNote)}><View style={[styles.icon, { backgroundColor: theme.accent.soft }]}><MaterialCommunityIcons name="note-edit-outline" size={24} color={theme.accent.base} /></View><View style={styles.copy}><Text style={[styles.optionTitle, { color: theme.content.primary }]}>Note</Text><Text style={[styles.optionText, { color: theme.content.secondary }]}>Write freely, format lists, and attach images</Text></View><Ionicons name="chevron-forward" size={19} color={theme.content.muted} /></TouchableOpacity><TouchableOpacity style={styles.option} onPress={() => choose(onCreateChecklist)}><View style={[styles.icon, { backgroundColor: theme.glass.secondary }]}><MaterialCommunityIcons name="checkbox-marked-outline" size={24} color={theme.content.primary} /></View><View style={styles.copy}><Text style={[styles.optionTitle, { color: theme.content.primary }]}>Checklist</Text><Text style={[styles.optionText, { color: theme.content.secondary }]}>Track steps, progress, and completed items</Text></View><Ionicons name="chevron-forward" size={19} color={theme.content.muted} /></TouchableOpacity></SafeAreaView></View></Modal>;
}

const styles = StyleSheet.create({ layer: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(10,10,10,.34)' }, sheet: { borderWidth: 1, borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingHorizontal: 20, paddingTop: 10, paddingBottom: 12 }, handle: { width: 38, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: 14 }, headingRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 }, title: { fontSize: 22, fontFamily: fontFamily.black }, subtitle: { marginTop: 3, fontSize: 12 }, close: { marginLeft: 'auto', width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, option: { minHeight: 78, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, gap: 12 }, icon: { width: 46, height: 46, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, optionTitle: { fontSize: 15, fontFamily: fontFamily.extrabold }, optionText: { marginTop: 3, fontSize: 12, lineHeight: 17 } });

