import { Platform, StyleSheet } from 'react-native';

import type { Theme } from '@/context/ThemeContext';
import { fontFamily } from '@/theme/typography';

export const makeStyles = (theme: Theme) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: 'transparent' },
  header: { minHeight: 68, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center' },
  headerButton: { width: 44, height: 44, marginLeft: -8, alignItems: 'center', justifyContent: 'center' },
  headerCopy: { flex: 1, marginLeft: 4 },
  headerTitle: { color: theme.content.primary, fontSize: 25, lineHeight: 31, fontFamily: fontFamily.black, letterSpacing: -0.5 },
  headerSubtitle: { color: theme.content.secondary, marginTop: 1, fontSize: 12, lineHeight: 16, fontFamily: fontFamily.medium },
  content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 40 },

  hero: {
    minHeight: 214,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: theme.glass.border,
    overflow: 'hidden',
    padding: 20,
  },
  heroGradient: { ...StyleSheet.absoluteFillObject },
  heroRailWide: {
    position: 'absolute',
    width: 250,
    height: 34,
    top: 18,
    right: -74,
    borderRadius: 17,
    backgroundColor: theme.dark ? 'rgba(237,237,239,0.07)' : 'rgba(255,255,255,0.28)',
    transform: [{ rotate: '-13deg' }],
  },
  heroRailFine: {
    position: 'absolute',
    width: 220,
    height: 1,
    right: -38,
    bottom: 43,
    backgroundColor: theme.dark ? 'rgba(237,237,239,0.11)' : 'rgba(255,255,255,0.56)',
    transform: [{ rotate: '-13deg' }],
  },
  avatar: { width: 82, height: 82, borderRadius: 41, overflow: 'visible' },
  avatarPhoto: { width: 82, height: 82, borderRadius: 41 },
  avatarFallback: { width: 82, height: 82, borderRadius: 41, alignItems: 'center', justifyContent: 'center' },
  avatarInitials: { color: theme.iconTile.foreground, fontSize: 25, lineHeight: 31, fontFamily: fontFamily.black },
  photoAction: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.iconTile.coral,
  },
  identity: { marginTop: 15, minWidth: 0 },
  name: { color: theme.content.primary, fontSize: 23, lineHeight: 29, fontFamily: fontFamily.black, letterSpacing: -0.4 },
  email: { color: theme.content.secondary, marginTop: 2, fontSize: 13, lineHeight: 18, fontFamily: fontFamily.medium },
  statusRow: { marginTop: 11, flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  statusPill: { minHeight: 30, borderRadius: 15, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', backgroundColor: theme.dark ? 'rgba(255,255,255,0.08)' : 'rgba(255,255,255,0.68)' },
  statusDot: { width: 7, height: 7, borderRadius: 4, marginRight: 6 },
  statusText: { color: theme.content.primary, fontSize: 11, lineHeight: 15, fontFamily: fontFamily.bold },
  editButton: { position: 'absolute', top: 20, right: 20, minHeight: 42, borderRadius: 21, paddingHorizontal: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.dark ? 'rgba(255,255,255,0.10)' : 'rgba(255,255,255,0.82)' },
  editButtonText: { color: theme.accent.pressed, fontSize: 13, lineHeight: 18, fontFamily: fontFamily.extrabold },

  section: { marginTop: 18 },
  sectionHeader: { marginBottom: 10, paddingHorizontal: 2 },
  sectionTitle: { color: theme.content.primary, fontSize: 17, lineHeight: 22, fontFamily: fontFamily.extrabold },
  sectionDescription: { color: theme.content.secondary, marginTop: 2, fontSize: 12, lineHeight: 16, fontFamily: fontFamily.medium },
  actionGroup: { borderRadius: 22, borderWidth: 1, borderColor: theme.glass.border, overflow: 'hidden', backgroundColor: theme.glass.primary },
  actionRow: { minHeight: 76, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center' },
  actionIcon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  actionCopy: { flex: 1, minWidth: 0, paddingRight: 10 },
  actionLabel: { color: theme.content.primary, fontSize: 15, lineHeight: 20, fontFamily: fontFamily.extrabold },
  actionDetail: { color: theme.content.secondary, marginTop: 2, fontSize: 12, lineHeight: 16, fontFamily: fontFamily.medium },
  divider: { height: StyleSheet.hairlineWidth, marginLeft: 68, backgroundColor: theme.divider },
  signOutButton: {
    minHeight: 50,
    marginTop: 18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.dark ? 'rgba(242,123,90,0.30)' : 'rgba(216,79,55,0.20)',
    backgroundColor: theme.dark ? 'rgba(242,123,90,0.10)' : 'rgba(252,229,222,0.72)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  signOutText: { color: theme.semantic.danger, fontSize: 14, lineHeight: 19, fontFamily: fontFamily.extrabold },
  version: { color: theme.content.muted, marginTop: 16, textAlign: 'center', fontSize: 11, lineHeight: 15, fontFamily: fontFamily.medium },

  modalLayer: { flex: 1, justifyContent: 'center', paddingHorizontal: 24, paddingVertical: 24 },
  modalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: theme.dark ? 'rgba(0,0,0,0.72)' : 'rgba(18,28,34,0.34)' },
  dialog: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: theme.glass.border,
    padding: 18,
    backgroundColor: theme.glass.solid,
    ...Platform.select({
      ios: { shadowColor: '#101A1B', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.12, shadowRadius: 20 },
      android: { elevation: 6 },
      default: {},
    }),
  },
  dialogTitle: { color: theme.content.primary, fontSize: 20, lineHeight: 25, fontFamily: fontFamily.extrabold },
  dialogCopy: { color: theme.content.secondary, marginTop: 4, fontSize: 13, lineHeight: 18, fontFamily: fontFamily.medium },
  inputLabel: { color: theme.content.secondary, marginTop: 16, marginBottom: 6, fontSize: 12, lineHeight: 16, fontFamily: fontFamily.bold },
  input: { minHeight: 52, borderRadius: 15, borderWidth: 1, borderColor: theme.glass.border, paddingHorizontal: 14, color: theme.content.primary, backgroundColor: theme.glass.secondary, fontSize: 16, fontFamily: fontFamily.semibold },
  dialogActions: { marginTop: 14, flexDirection: 'row', gap: 8 },
  cancelButton: { flex: 1, minHeight: 46, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.glass.secondary },
  cancelText: { color: theme.content.primary, fontSize: 14, lineHeight: 19, fontFamily: fontFamily.extrabold },
  saveButton: { flex: 1.35, minHeight: 46, borderRadius: 15, flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.accent.base },
  saveText: { color: theme.iconTile.foreground, fontSize: 14, lineHeight: 19, fontFamily: fontFamily.extrabold },
  disabled: { opacity: 0.5 },
});
