import { fontFamily } from '@/theme/typography';
import { StyleSheet } from 'react-native';

export const pom = StyleSheet.create({
  scroll: { paddingTop: 8, paddingHorizontal: 20, paddingBottom: 124, gap: 14 },
  timerCard: { width: '100%', borderRadius: 28, borderWidth: 1, paddingHorizontal: 18, paddingTop: 16, paddingBottom: 20, alignItems: 'center', overflow: 'hidden' },
  modePills: { width: '100%', minHeight: 44, flexDirection: 'row', padding: 4, borderRadius: 22 },
  modePill: { flex: 1, minHeight: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  modePillText: { fontSize: 13, fontFamily: fontFamily.bold },
  ringWrap: { width: 220, height: 220, alignItems: 'center', justifyContent: 'center', marginTop: 22, marginBottom: 20 },
  ringCenter: { position: 'absolute', alignItems: 'center' },
  modeLabel: { fontSize: 13, fontFamily: fontFamily.bold, marginBottom: 3 },
  digits: { fontSize: 48, fontFamily: fontFamily.extrabold, letterSpacing: -1.5, lineHeight: 56, fontVariant: ['tabular-nums'] as any },
  statusPill: { minHeight: 28, borderRadius: 14, marginTop: 6, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 6 },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  runSub: { fontSize: 11, fontFamily: fontFamily.bold },
  controls: { flexDirection: 'row', alignItems: 'center', gap: 26 },
  ctrlBtn: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' },
  playBtn: { width: 66, height: 66, borderRadius: 33, alignItems: 'center', justifyContent: 'center' },
  statsRow: { flexDirection: 'row', alignItems: 'center', width: '100%', borderRadius: 22, borderWidth: 1, paddingVertical: 15 },
  statItem: { flex: 1, alignItems: 'center' },
  statDivider: { width: StyleSheet.hairlineWidth, height: 34 },
  statVal: { fontSize: 20, fontFamily: fontFamily.extrabold, marginBottom: 2 },
  statLabel: { fontSize: 10, fontFamily: fontFamily.semibold },
  contextCard: { width: '100%', borderRadius: 22, borderWidth: 1, padding: 16 },
  contextHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  contextIcon: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  contextHeaderCopy: { flex: 1 },
  contextTitle: { fontSize: 16, fontFamily: fontFamily.extrabold },
  contextSubtitle: { marginTop: 2, fontSize: 11, lineHeight: 16 },
  linkBtn: { minHeight: 48, marginTop: 14, borderRadius: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  linkBtnText: { fontSize: 14, fontFamily: fontFamily.bold },
  linkedNote: { marginTop: 14, borderRadius: 17, overflow: 'hidden' },
  linkedMain: { minHeight: 72, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 10 },
  linkedCopy: { flex: 1 },
  linkedLabel: { fontSize: 8, letterSpacing: 1, fontFamily: fontFamily.black },
  linkedTitle: { marginTop: 3, fontSize: 15, fontFamily: fontFamily.extrabold },
  linkedMeta: { marginTop: 2, fontSize: 10 },
  linkActions: { minHeight: 44, flexDirection: 'row', borderTopWidth: StyleSheet.hairlineWidth },
  linkAction: { flex: 1, minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  linkActionText: { fontSize: 12, fontFamily: fontFamily.bold },
  pickerOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)' },
  pickerSheet: { borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingTop: 9, paddingHorizontal: 20, paddingBottom: 32, maxHeight: '68%' },
  pickerHandle: { width: 42, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: 14 },
  pickerHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  pickerTitle: { fontSize: 20, fontFamily: fontFamily.extrabold },
  pickerSubtitle: { marginTop: 2, fontSize: 11 },
  pickerClose: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  pickerRow: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: StyleSheet.hairlineWidth },
  pickerNoteIcon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
  pickerRowCopy: { flex: 1 },
  pickerRowText: { fontSize: 14, fontFamily: fontFamily.extrabold },
  pickerRowMeta: { marginTop: 2, fontSize: 10 },
  pickerEmpty: { paddingVertical: 24, alignItems: 'center' },
  pickerEmptyTitle: { fontSize: 16, fontFamily: fontFamily.extrabold },
  pickerEmptyText: { maxWidth: 260, marginTop: 5, fontSize: 12, lineHeight: 18, textAlign: 'center' },
  pickerOpenNotes: { minHeight: 48, marginTop: 16, borderRadius: 24, paddingHorizontal: 22, alignItems: 'center', justifyContent: 'center' },
  pickerOpenNotesText: { color: '#FFFFFF', fontSize: 14, fontFamily: fontFamily.extrabold },
});


export const sw = StyleSheet.create({
  root: { flex: 1, alignItems: 'center', paddingHorizontal: 20 },
  displayWrap: { flex: 1, minHeight: 180, alignItems: 'center', justifyContent: 'center', paddingTop: 12 },
  digits: { fontSize: 58, lineHeight: 68, fontFamily: fontFamily.light, letterSpacing: -1, fontVariant: ['tabular-nums'] as any },
  lapHint: { fontSize: 16, marginTop: 10 },
  btnRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 28, paddingTop: 16, paddingBottom: 20,
  },
  sideBtn: {
    width: 78, height: 78, borderRadius: 39,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1,
  },
  sideBtnText: { fontSize: 17, fontFamily: fontFamily.semibold },
  mainBtn: {
    width: 78, height: 78, borderRadius: 39,
    alignItems: 'center', justifyContent: 'center',
  },
  mainBtnText: { fontSize: 17, fontFamily: fontFamily.bold, color: '#fff' },
  lapList: { width: '100%', maxHeight: 220 },
  lapRow: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 24, paddingVertical: 13,
    borderTopWidth: 1,
  },
  lapNum: { width: 60, fontSize: 15 },
  lapSplit: { flex: 1, fontSize: 15, fontFamily: fontFamily.semibold, textAlign: 'center', fontVariant: ['tabular-nums'] as any },
  lapTotal: { width: 90, fontSize: 14, textAlign: 'right', fontVariant: ['tabular-nums'] as any },
});


export const main = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 14,
    borderBottomWidth: 0,
  },
  headerTitle: { fontSize: 20, fontFamily: fontFamily.bold },
  headerAction: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  tabBar: {
    flexDirection: 'row',
    marginHorizontal: 20, marginVertical: 12,
    borderRadius: 999, padding: 4, borderWidth: 1,
  },
  tabBtn: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 6, paddingVertical: 10, borderRadius: 11,
  },
  tabBtnActive: {},
  tabText: { fontSize: 14, fontFamily: fontFamily.semibold },
  tabTextActive: {},
});
